# Generated by Django 4.0.4 on 2022-05-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
